services:
  web_nginx:
    image: nginx
    container_name: nginx_server

    volumes:
      - ./server/nginx/conf:/etc/nginx/conf.d
      - ./server/nginx/html:/server/nginx/www/html

    restart: always

    ports:
      - 80:80

  db:
    image: mysql:5.7
    container_name: mysql_db
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password


  web_apache:
    container_name: apache_server

    volumes:
      - ./server/apache/confs/apache2.conf:/etc/apache2/apache2.conf
      - ./server/apache/confs/access/.group:/etc/apache2/.group
      - ./server/apache/confs/access/.htpasswd:/etc/apache2/.htpasswd
      - ./server/apache/site_available:/etc/apache2/sites-available
      - ./server/apache/test:/server/apache/test
    build:
      context: ./server
      dockerfile: Dockerfile

    restart: always

    ports:
      - 8000:80
      
    depends_on:
      - db